---
- name: Provision Instances
  hosts: localhost
  gather_facts: false
  tags:
    - instances
    - smoketest
  roles:
    - role: provision-osp
    - role: in-memory

- name: Add DNS Information
  hosts: osp_instances
  become: true
  gather_facts: false
  tags:
    - instances
    - instances_config
  roles:
    - role: dns_resolv
    - role: satellite_regi

- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  roles:
    - role: database

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
    
  roles:
    - role: app

- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  become: true
  tags:
    - load_balancers
  roles:
    - role: loadbalance


- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  vars:
    do_smoke_test: db
  tags:
    - smoketest
  roles:
    - role: smoke_test

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  vars:
    do_smoke_test: web
  tags:
    - smoketest  
  roles:
    - role: smoke_test
